### PR TITLE
Passing submodel name as a parameter for metrics generation so it identifies the right location of metrics folder

### PR DESCRIPTION
**Pull request by notprathap**
Code is self-descriptive

### CODE REVIEW

**Comment by notprathap** [comment]
@microsoft-github-policy-service agree

**Comment by geflaspohler** [comment]
Thank you for your contribution, @notprathap  - can you please share an example command that generates the error you're addressing with the submodel name in metrics generation?

**Comment by notprathap** [comment]
@geflaspohler running the demo command:

`python -m subseasonal_toolkit.generate_predictions -t std_paper_forecast -u -e -m raw_cfsv2 --task us_tmp2m_1.5x1.5_34w`

creates models correctly but metrics generation fails with the message NameError: name 'lat_lon_skill_u' is not defined

**Comment by paulo-o** [comment]
@notprathap, I believe the NameError happens because the necessary raw_cfsv2 forecasts haven't been created. Can you share the whole error stack trace so we can understand what the root cause is?

**Comment by notprathap** [comment]
Warning: None/us_tmp2m_1.5x1.5_34w-20211224.h5 does not exist; skipping
Getting metrics for 2021-12-25 00:00:00
20211225
Warning: None/us_tmp2m_1.5x1.5_34w-20211225.h5 does not exist; skipping
Getting metrics for 2021-12-26 00:00:00
20211226
Warning: None/us_tmp2m_1.5x1.5_34w-20211226.h5 does not exist; skipping
Getting metrics for 2021-12-27 00:00:00
20211227
Warning: None/us_tmp2m_1.5x1.5_34w-20211227.h5 does not exist; skipping
Getting metrics for 2021-12-28 00:00:00
20211228
Warning: None/us_tmp2m_1.5x1.5_34w-20211228.h5 does not exist; skipping
Getting metrics for 2021-12-29 00:00:00
20211229
Warning: None/us_tmp2m_1.5x1.5_34w-20211229.h5 does not exist; skipping
Getting metrics for 2021-12-30 00:00:00
20211230
Warning: None/us_tmp2m_1.5x1.5_34w-20211230.h5 does not exist; skipping
Getting metrics for 2021-12-31 00:00:00
20211231
Warning: None/us_tmp2m_1.5x1.5_34w-20211231.h5 does not exist; skipping
Traceback (most recent call last):
  File "/Users/pchandran/Code/sandbox/subseasonal_toolkit/subseasonal_toolkit/batch_metrics.py", line 280, in <module>
    l = [(1 - cosine(lat_lon_skill_u.loc[i], lat_lon_skill_v.loc[i])) for i in lat_lon_skill_u.index]  
                                                                               ^^^^^^^^^^^^^^^
NameError: name 'lat_lon_skill_u' is not defined

**Comment by notprathap** [comment]
As you can see, it's looking at a directory that doesn't exist.

What do you see when you run 
`python -m subseasonal_toolkit.generate_predictions -t std_paper_forecast -u -e -m raw_cfsv2 --task us_tmp2m_1.5x1.5_34w` ? (I have set the SUBSEASONALDATA_PATH env variable to a local folder, in case you were wondering)

**Comment by paulo-o** [comment]
If you pull the newest commit that error should disappear, but only because it was being caused by non-existent forecasts, which will still be an issue. For some reason the code is looking for predictions in the folder "None/". I believe this is due to the outcome of `get_task_forecast_dir()` in line 63 of `batch_metrics.py` which, in turn, returns `None` if the the output of `get_selected_submodel_name()` in line 88 of `models_util.py` is `None`. This is likely being caused by the failure in reading the module in line 27 of `models_util.py`. Can you check the relevant file exists and that the attributes are being properly read? In the example above, the file is `subseasonal_toolkit/models/raw_cfsv2/attributes.py` ([here](https://github.com/microsoft/subseasonal_toolkit/blob/23f621685cc10906cf23f3451bfdde5de05365ad/subseasonal_toolkit/models/raw_cfsv2/attributes.py)).

**Pull request closed without merging**
